### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by jacwright** [typewriter-editor/typewriter#106]
Running `npm test` gives this error:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /.../typewriter/test/dom.test.ts
```

The fixes online all suggest to remove `"type": "module",` from `package.json`. Should we give up on modules and stick with commonjs output?

**Comment by jacwright** [comment]
Related to #100 and #101

**Comment by taylorhadden** [comment]
In some of my projects, I have a working setup with `"type": "module"`, typescript, and Jest. I could convert the project and tests over.

Would you be interested in that?

**Comment by jacwright** [comment]
Vite & Vitest are the best today for working with ESM. Jest worked alright but still had more headaches than Vitest did.
