### ISSUE TITLE
Setup CI and increase test coverage

### ISSUE THREAD

**Issue by seanfcarroll** [typewriter-editor/typewriter#15]
Assign to seanfcarroll.

I will use Travis if there are no objections. They have a free plan for open source.

**Comment by jacwright** [comment]
Let me know what I need to add to webhooks settings.

**Comment by seanfcarroll** [comment]
As I'm now in the repo, I think I can set it up. :-)

**Comment by seanfcarroll** [comment]
Implemented, added Code Climate also. Tests currently failing, will see if I can fix them.

**Comment by jacwright** [comment]
I found the issue. The `.babelrc` file I had locally wasn't committed because of the gitignore rules. I got it in there now and the builds should pass.
