### ISSUE TITLE
Add a linter to the build pipeline

### ISSUE THREAD

**Issue by seanfcarroll** [typewriter-editor/typewriter#37]
Not sure what is best for this project, or if there is anything like [RuboCop](https://github.com/bbatsov/rubocop) available for npm projects. The advantage of Rubocop is it can be configured to meet your personal style, but then it is enforced project-wide.

https://twitter.com/lucasmazza/status/705866469956001793?lang=en

**Comment by jacwright** [comment]
We've moved to Typescript. Is this sufficient?
