### ISSUE TITLE
Menu module

### ISSUE THREAD

**Issue by seanfcarroll** [typewriter-editor/typewriter#41]
An easily extendable and configurable menu module, with all building blocks easily accessible to end-user devs. The Prosemirror menu config is quite to follow, while the Quill version is a good model.

I **love** [this project's](https://chuckh.github.io/polymer-quill/components/polymer-quill/demo/firebase.html) bubble menu.

<img width="940" alt="screen shot 2018-04-26 at 09 46 20" src="https://user-images.githubusercontent.com/11340230/39292558-d0338ab2-4936-11e8-8a86-eb28bff2a697.png">

[Source code](https://github.com/chuckh/polymer-quill/blob/master/polymer-quill-bubble-firebase.html)

**Comment by jacwright** [comment]
The new renderless BubbleMenu allows for this to be created. It may be useful to create several full implementations like this here as both examples of what can be done as well as quick-grab solutions.
