### ISSUE TITLE
What is the recommended way to store data in a database/create a controlled editor component?

### ISSUE THREAD

**Issue by HemalR** [typewriter-editor/typewriter#66]
Hi,

Thank you very much for a great looking library! I'm tossing up between options to use and gravitated to this since I'm using Svelte for the front-end.

I had a couple of questions (and am happy to convert the answers into an example for others in the example repo as a new tab as well as on Stackblitz):

1. What is the recommended way to store editor content into a database for persistence? I played around with using `editor.getText()` and wiring that up to change event, which works but will only store simple text. Would a similar pattern storing the entire doc be the way to go?
2. Is it possible to add additional custom attributes to lines? Either manually or as a middleware function that could apply to the full editor and all lines in it? I'm thinking, for example, of an `updatedAt` attribute for each line.

Thanks again for the great lib!

**Comment by jacwright** [comment]
1. `editor.getHTML()` and `editor.setHTML(value)` would work better for rich text. If you can save JSON to your store, saving `editor.doc` and restoring it with `editor.set(doc)` is even better.
2. there is a `changedLines` array in the `EditorChangeEvent` you may be able to use to add `updatedAt` to the line attributes. You can create a module which gives you an `init` and `destroy` method for easier cleanup.

Something like

```js
export function addDate(editor) {
  function onChange(event) {
    if (event.changedLines) {
      event.changedLines.forEach(line => line.attributes.updatedAt = Date.now());
    }
  }

  return {
    init() {
      editor.on('change', onChange);
    },
    destroy() {
      editor.off('change', onChange);
    }
  }
}
```

**Comment by jacwright** [comment]
For questions, let's try and use the discussions tab. I've not really used it before, but I'd like to try it out and see how it goes.
